# Replica settings
replicaCount: 1

# Container image
image:
  repository: pn02ci/reservationservice
  pullPolicy: IfNotPresent
  tag: dev-amd64

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

# ServiceAccount
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod metadata
podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# Service
service:
  type: ClusterIP
  port: 8080

# Ingress (disabled by default)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: reservation.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# App configuration
env:
  ASPNETCORE_ENVIRONMENT: "Development"
  Kestrel__Endpoints__Http__Url: "http://0.0.0.0:8080"
  OpenTelemetry__Enabled: "true"
  OpenTelemetry__Exporter: "otlp"
  OpenTelemetry__Otlp__Endpoint: "http://otel-collector:4317"
  Services__StationService__BaseUrl: "http://stationservice:8080"
  Database__ConnectionString: "Server=192.168.1.191;Port=5432;Database=reservation_db;User Id=admin;Password=admin"
  RabbitMq__Host: "rabbitmq.rabbitmq.svc.cluster.local"
  RabbitMq__Port: "5672"
  RabbitMq__Username: "admin"
  RabbitMq__Password: "supersecret"
  RabbitMq__Exchange: "ev.platform"

connectionStrings:
  postgres: "Server=192.168.1.191;Port=5432;Database=reservation_db;User Id=admin;Password=admin"

# Probes
livenessProbe:
  httpGet:
    path: /health/live
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health/ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# HPA
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

networkPolicy:
  enabled: true
  postgresCidr: "192.168.1.191/32"
  postgresPort: 5432
  rabbitmq:
    # Override these selectors if your RabbitMQ release uses different labels/namespace
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: rabbitmq
    podSelector:
      app.kubernetes.io/name: rabbitmq
    port: 5672

nodeSelector: {}
tolerations: []
affinity: {}
