apiVersion: apps/v1
kind: Deployment
metadata:
  name: stationservice
  namespace: ev-platform-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stationservice
  template:
    metadata:
      labels:
        app: stationservice
    spec:
      containers:
        - name: stationservice
          image: station-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: stationservice-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: Kestrel__Endpoints__Http__Url
              valueFrom:
                configMapKeyRef:
                  name: stationservice-config
                  key: Kestrel__Endpoints__Http__Url
            - name: ConnectionStrings__Postgres
              valueFrom:
                secretKeyRef:
                  name: stationservice-secret
                  key: ConnectionStrings__Postgres
            - name: App__Name
              valueFrom:
                configMapKeyRef:
                  name: stationservice-config
                  key: App__Name
            - name: App__Version
              valueFrom:
                configMapKeyRef:
                  name: stationservice-config
                  key: App__Version
            - name: App__Environment
              valueFrom:
                configMapKeyRef:
                  name: stationservice-config
                  key: App__Environment
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
