apiVersion: v1
kind: Secret
metadata:
  name: reservationservice-secret
  namespace: ev-platform-dev
type: Opaque
stringData:
  ConnectionStrings__Postgres: "Host=192.168.1.191;Port=5432;Database=reservation_db;Username=admin;Password=admin"
