apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ev-platform-ingress
  namespace: ev-platform-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /station(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: stationservice-api
                port:
                  number: 80
          - path: /reservation(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: reservationservice-api
                port:
                  number: 80
