apiVersion: v1
kind: Service
metadata:
  name: {{ include "reservationservice.fullname" . }}-api
  labels:
    {{- include "reservationservice.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "reservationservice.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
