{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stationservice.fullname" . }}-secret
  labels:
    {{- include "stationservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Postgres: "{{ .Values.secrets.postgresConnection }}"
{{- end }}
