apiVersion: v2
name: ev-platform
description: Umbrella chart for EV Platform services
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: stationservice
    version: 0.1.0
    repository: "file://../stationservice"
  - name: reservationservice
    version: 0.1.0
    repository: "file://../reservationservice"
