stationservice:
  image:
    tag: latest
  secrets:
    postgresConnection: "Host=192.168.1.191;Port=5432;Database=station_db;Username=admin;Password=admin"
  env:
    aspnetcoreEnvironment: Development
    kestrelUrl: http://0.0.0.0:8080
    app:
      name: station-service
      version: 1.0.0
      environment: Development

reservationservice:
  image:
    tag: latest
  secrets:
    postgresConnection: "Host=192.168.1.191;Port=5432;Database=reservation_db;Username=admin;Password=admin"
  env:
    aspnetcoreEnvironment: Development
    kestrelUrl: http://0.0.0.0:8080
    app:
      name: reservation-service
      version: 1.0.0
      environment: Development
    services:
      stationServiceBaseUrl: http://stationservice-api.ev-platform-dev.svc.cluster.local
