apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adminconfigservice.fullname" . }}-secret
type: Opaque
stringData:
  ConnectionStrings__Postgres: {{ .Values.env.ConnectionStrings__Postgres | quote }}
