{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "billingservice.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "billingservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
