apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reservationservice.fullname" . }}-config
  labels:
    {{- include "reservationservice.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.env.aspnetcoreEnvironment }}"
  Kestrel__Endpoints__Http__Url: "{{ .Values.env.kestrelUrl }}"
  Services__StationService__BaseUrl: "{{ .Values.env.services.stationServiceBaseUrl }}"
  App__Name: "{{ .Values.env.app.name }}"
  App__Version: "{{ .Values.env.app.version }}"
  App__Environment: "{{ .Values.env.app.environment }}"
