{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reservationservice.fullname" . }}-secret
  labels:
    {{- include "reservationservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Postgres: "{{ .Values.secrets.postgresConnection }}"
{{- end }}
