{{- if .Values.connectionStrings.postgres }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "billingservice.fullname" . }}-secret
  labels:
    {{- include "billingservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Postgres: {{ .Values.connectionStrings.postgres | quote }}
{{- end }}
